### ISSUE TITLE
include note regarding renaming of VirtualBox folder

### ISSUE THREAD

**Issue by hiddenillusion** [vortessence/vortessence#1]
When using the Vagrant method to run vortessence, I was able to successfully issue the `vagrant up`  command but I tried the next command, `vagrant ssh`, I received the error:
<code>
The provider 'VirtualBox' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
</code>

After seeing this issue (https://github.com/mitchellh/vagrant/issues/5189) I simply (or sadly) renamed  _.vagrant/machines/default/VirtualBox_ to _.vagrant/machines/default/virtualbox_ and it worked. This seems to be some glitch with Vagrant but this might be worth mentioning as a side note or troubleshooting note for others.

**Comment by burech** [comment]
Thanks for testing Vortessence and the hint regarding this Vagrant issue! I added a note under `vagrant ssh` on the page.
