### ISSUE TITLE
include note for creating ramdisk in Vagrant installation

### ISSUE THREAD

**Issue by hiddenillusion** [vortessence/vortessence#2]
In the manual installation notes you mention the syntax `sudo sh -c 'echo "tmpfs /media/tmpfs tmpfs defaults,size=3072M 0 0" >> /etc/fstab'` to create a ramdisk but if you use the Vagrant installation method this is automatically issued via `vagrant/provision.sh` - so, if you just follow the installation instructions as they currently are you're only going have a 3GB ramdisk created which won't work well if you're analyzing a memory dump > 3GB since you'll run out of space since the entire memory dump is copied to that ramdisk via `/vagrant/vortessence/vortessence/acquisition/memory_dump.py`

**Comment by burech** [comment]
Thanks for the note! There are now some lines regarding the limitations of the Vagrant VM and how they can be overcome.
